### ISSUE TITLE
Roadmap of future changes to CNModel

### ISSUE THREAD

**Issue by campagnola** [cnmodel/cnmodel#4]
# Roadmap of future changes to cnmodel

(Edit as needed)

- [ ] Unit tests for physiological response properties (see #3)
- [ ] Update AN model for mouse (see: Taberner & Liberman 2005)
- [ ] Update synapse models for physiological conditions (particularly calcium concentration)
- [ ] Implement Syn2Exp as default for all synapses
    - [ ] Generalize synapse construction code, move to Cell class (too much code copied between cell subclasses)
- [ ] Independent random streams for all random processes [1,2].
    - [ ] unit tests to ensure the network model has identical behavior for serial and parallel runs
    - [ ] Remove all usage of global number generators
    - [ ] Use a global seed--user should be able to set only one seed and have that set the state of the entire simulation 
    - [ ] Every time a random stream is seeded, the global seed must be xor'd with a number that is unique to that location in the code (this prevents independent RNG streams from drawing the same random numbers)
    - [ ] Every time we run a simulation, the global seed must be incremented
- [x] Reference management to avoid leaked sections and mechanisms
- [ ] Better connectivity estimates 
- [x] TV cell model
- [ ] Add cochlear implant model
- [x] Add MSO model
- [ ] Add MSO cells to populations. 
- [ ] Add tapered dendrites to MSO cell and segregate inputs by ear (per Scott et al., J. Neurosci. 2017). 
- [ ] Capture all simulation parameters for a given run.

[1]  http://www.neuron.yale.edu/neuron/node/62
[2]  http://senselab.med.yale.edu/modeldb/ShowModel.asp?model=156780&file=%5CProbUDFsyn2.mod
